import { execFileSync } from "child_process";
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import vm from "vm";

const ROOT = new URL("../..", import.meta.url).pathname;
const XLSX_FILE = join(ROOT, "Sports Translations.xlsx");
const CATEGORY_MAP_FILE = join(ROOT, "src/lib/workoutCategoryMap.ts");
const OUT_FILE = join(ROOT, "src/lib/workoutTitleSpreadsheetMap.ts");

function normalizeKey(value = "") {
  return value.trim().replace(/\s+/gu, " ");
}

function decodeXml(value = "") {
  return value
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_match, code) => String.fromCodePoint(Number(code)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_match, code) =>
      String.fromCodePoint(Number.parseInt(code, 16)),
    );
}

function extractObjectLiteral(file, varName) {
  const src = readFileSync(file, "utf-8");
  const match = src.match(
    new RegExp(`export const ${varName}[^=]*=\\s*({[\\s\\S]*?^});`, "m"),
  );
  if (!match) throw new Error(`Unable to find ${varName} in ${file}`);
  return vm.runInNewContext(`(${match[1]})`);
}

function readWorksheetRows(xlsxFile) {
  const xml = execFileSync("unzip", ["-p", xlsxFile, "xl/worksheets/sheet1.xml"], {
    encoding: "utf-8",
  });

  const rows = [];
  const rowPattern = /<row[^>]*>([\s\S]*?)<\/row>/g;
  const cellPattern = /<c\b[^>]*r="([A-Z]+)\d+"[^>]*>([\s\S]*?)<\/c>/g;
  const inlineValuePattern = /<is><t[^>]*>([\s\S]*?)<\/t><\/is>/;
  const valuePattern = /<v>([\s\S]*?)<\/v>/;

  for (const rowMatch of xml.matchAll(rowPattern)) {
    const cells = [];
    for (const cellMatch of rowMatch[1].matchAll(cellPattern)) {
      const ref = cellMatch[1];
      const payload = cellMatch[2];
      const inlineValue = payload.match(inlineValuePattern)?.[1];
      const rawValue = inlineValue ?? payload.match(valuePattern)?.[1] ?? "";
      cells.push([ref, decodeXml(rawValue)]);
    }
    if (cells.length > 0) rows.push(cells);
  }

  return rows;
}

const rows = readWorksheetRows(XLSX_FILE);
const categoryMap = extractObjectLiteral(CATEGORY_MAP_FILE, "workoutCategoryMap");
const categoryKeys = new Set(Object.keys(categoryMap));

const entries = [];
for (const row of rows.slice(1)) {
  const values = Object.fromEntries(row);
  const german = normalizeKey(values.A ?? "");
  if (!german || categoryKeys.has(german)) continue;

  entries.push([
    german,
    {
      en: normalizeKey(values.B ?? ""),
      ja: normalizeKey(values.C ?? ""),
      ko: normalizeKey(values.D ?? ""),
      "zh-CN": normalizeKey(values.E ?? ""),
    },
  ]);
}

entries.sort(([left], [right]) => left.localeCompare(right));

const renderedEntries = entries
  .map(([key, locales]) => {
    const body = Object.entries(locales)
      .filter(([, value]) => value)
      .map(
        ([locale, value]) => `    ${JSON.stringify(locale)}: ${JSON.stringify(value)},`,
      )
      .join("\n");
    return `  ${JSON.stringify(key)}: {\n${body}\n  },`;
  })
  .join("\n");

const output = `// Auto-generated by src/scripts/generateTitleSpreadsheetMap.mjs — do not edit manually.
// Re-run: node src/scripts/generateTitleSpreadsheetMap.mjs

import type { SidebarLocale } from "./workoutSidebarI18n";
import type { LocalizedLabelMap } from "./workoutI18nUtils";

export const workoutTitleSpreadsheetMap: LocalizedLabelMap<SidebarLocale> = {
${renderedEntries}
};
`;

writeFileSync(OUT_FILE, output, "utf-8");
console.log(`Wrote ${entries.length} spreadsheet title entries to ${OUT_FILE}`);
