import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const ROOT = new URL("../..", import.meta.url).pathname;

const DE_DIR = join(ROOT, "docs/workouts");
const LOCALE_DIRS = {
  en: join(ROOT, "docs/en/workouts"),
  ja: join(ROOT, "docs/ja/workouts"),
  ko: join(ROOT, "docs/ko/workouts"),
  "zh-CN": join(ROOT, "docs/zh-cn/workouts"),
};
const OUT_FILE = join(ROOT, "src/lib/workoutTitleMap.ts");

function extractHeadings(content) {
  return content
    .split("\n")
    .filter((line) => line.startsWith("## "))
    .map((line) => line.slice(3).trim());
}

const mapping = {};
let mismatches = 0;

const files = readdirSync(DE_DIR)
  .filter((f) => f.endsWith(".md") && f !== "index.md")
  .sort();

for (const file of files) {
  const deHeadings = extractHeadings(
    readFileSync(join(DE_DIR, file), "utf-8"),
  );

  for (const [locale, dir] of Object.entries(LOCALE_DIRS)) {
    let localeHeadings;
    try {
      localeHeadings = extractHeadings(readFileSync(join(dir, file), "utf-8"));
    } catch {
      continue;
    }

    if (localeHeadings.length !== deHeadings.length) {
      console.warn(
        `[${locale}] ${file}: heading count mismatch` +
        ` (de=${deHeadings.length}, ${locale}=${localeHeadings.length})`,
      );
      mismatches++;
    }

    const len = Math.min(deHeadings.length, localeHeadings.length);
    for (let i = 0; i < len; i++) {
      const de = deHeadings[i];
      const loc = localeHeadings[i];
      if (!loc || loc === de) continue;
      if (!mapping[de]) mapping[de] = {};
      mapping[de][locale] = loc;
    }
  }
}

const entries = Object.entries(mapping)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([de, locales]) => {
    const inner = Object.entries(locales)
      .map(([lang, title]) => `    ${JSON.stringify(lang)}: ${JSON.stringify(title)},`)
      .join("\n");
    return `  ${JSON.stringify(de)}: {\n${inner}\n  },`;
  })
  .join("\n");

const output = `\
// Auto-generated by src/scripts/generateTitleMap.mjs — do not edit manually.
// Re-run:  node src/scripts/generateTitleMap.mjs

import type { SidebarLocale } from "./workoutSidebarI18n";

export const workoutTitleMap: Record<
  string,
  Partial<Record<SidebarLocale, string>>
> = {
${entries}
};
`;

writeFileSync(OUT_FILE, output, "utf-8");

console.log(
  `Wrote ${Object.keys(mapping).length} entries to src/lib/workoutTitleMap.ts` +
  (mismatches
    ? `  (${mismatches} heading-count mismatches — review warnings above)`
    : ""),
);
